### ISSUE TITLE
安装依赖后，一直报 GitWrapper\GitException

### ISSUE THREAD

**Issue by felix9ia** [wi1dcard/weekly-report#2]
```
Fatal error: Uncaught GitWrapper\GitException: git: 'config --global user.name' is not a git command. See 'git --help'.
 in /Users/jiapengfei/felix-doc/weekly-report/toolkit/vendor/cpliakas/git-wrapper/src/GitProcess.php:83
Stack trace:
#0 /Users/jiapengfei/felix-doc/weekly-report/toolkit/vendor/symfony/process/Process.php(238): GitWrapper\GitProcess->wait()
#1 /Users/jiapengfei/felix-doc/weekly-report/toolkit/vendor/cpliakas/git-wrapper/src/GitWrapper.php(312): Symfony\Component\Process\Process->run(Object(Closure))
#2 /Users/jiapengfei/felix-doc/weekly-report/toolkit/vendor/cpliakas/git-wrapper/src/GitWrapper.php(300): GitWrapper\GitWrapper->run(Object(GitWrapper\GitCommand))
#3 /Users/jiapengfei/felix-doc/weekly-report/toolkit/helpers.php(57): GitWrapper\GitWrapper->git('config --global...')
#4 /Users/jiapengfei/felix-doc/weekly-report/toolkit/config.php(8): git_get_author()
#5 /Users/jiapengfei/felix-doc/weekly-report/toolkit/today(8): require('/Users/jiapengf...')
#6 {main}

```

**Comment by wi1dcard** [comment]
请手动执行 `git config --global user.name` 看是否有报错。
